=== athidevwork/demo/oasis/web/ePolicy/config/dti/pageEntitlements.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="EnabledOrDisabledOrHideOrShow">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Enabled/Disabled"/>
            <xsd:enumeration value="Disabled/Enabled"/>
            <xsd:enumeration value="Hide/Show"/>
            <xsd:enumeration value="Show/Hide"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="DefaultEnabledOrDisabledOrHideOrShow">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Enabled"/>
            <xsd:enumeration value="Disabled"/>
            <xsd:enumeration value="Hide"/>
            <xsd:enumeration value="Show"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="PageOrRow">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Page"/>
            <xsd:enumeration value="Row"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="tag">
        <xsd:complexType>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="indFieldName" type="xsd:string" use="required"/>
            <xsd:attribute name="indFieldLocation" type="PageOrRow" use="required"/>
            <xsd:attribute name="gridId" type="xsd:string" use="optional"/>
            <xsd:attribute name="action" type="EnabledOrDisabledOrHideOrShow" use="required"/>
            <xsd:attribute name="defaultActionForNoRows" type="DefaultEnabledOrDisabledOrHideOrShow"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="tags">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tag" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="page">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tags" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
            <xsd:attribute name="pageURI" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="pageEntitlement">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="page" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== athidevwork/demo/oasis/web/eCIS/config/dti/pageEntitlements.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pageEntitlement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="pageEntitlements.xsd">
    <page pageURI="">
        <tags>
        </tags>
    </page>

    <page pageURI="/CIS/ciAgent.do">
        <tags>
            <tag id="CI_AGENT_PAY_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="payListGrid"/>
            <tag id="CI_AGENT_CONT_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="contractListGrid"/>
            <tag id="CI_AGENT_COMM_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="commissionListGrid"/>
            <tag id="CI_AGENT_STAFF_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="agentStaffListGrid"/>
            <tag id="agentStaffEntityName" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="agentStaffListGrid"/>
            <tag id="CI_AGENT_STAFF_OVRD_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="agentStaffOverrideListGrid"/>
            <tag id="CI_AGENT_SUB_PRODUCER" indFieldName="isSubProducerAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="contractListGrid"/>
            <tag id="CI_AGENT_OUTPUT" indFieldName="isOutputAvailable" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="CI_AGENT_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_AGENT_CONT_ADD" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_AGENT_PAY_ADD" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_AGENT_STAFF_ADD" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>

    <page pageURI="/CIS/amalgamationmgr/maintainAmalgamation.do">
        <tags>
            <tag id="CI_AMALGAMATION_DELETE" indFieldName="isDeleteAvailable" indFieldLocation="Row"
                 action="Enabled/Disabled" defaultActionForNoRows="Disabled" gridId="amalgamationListGrid" />
        </tags>
    </page>

    <page pageURI="/disciplinedeclinemgr/maintainDisciplineDecline.do">
        <tags>
            <tag id="effectiveFromDate" indFieldName="isDeleteAvailable" indFieldLocation="Row" action="Enabled/Disabled"
                 defaultActionForNoRows="Disabled"/>
            <tag id="CS_DDL_DELETE" indFieldName="isDeleteAvailable" indFieldLocation="Row" action="Enabled/Disabled"
                 defaultActionForNoRows="Disabled"/>
            <tag id="CS_DDL_ADD" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CS_DDL_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CS_DDL_SAVE_PUP" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>
    <page pageURI="/ciEntityAdditional.do">
        <tags>
            <tag id="facilityName" indFieldName="medicalDirectorB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="prisonExposureTime" indFieldName="prisonExposureB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="positionAtFacility" indFieldName="medicalDirectorB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="otherCoveragePositionB" indFieldName="medicalDirectorB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="pctWcPractice" indFieldName="treatsWcB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="numberPathologyInterpret" indFieldName="dermatologistB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="emergencyTime" indFieldName="emergencyActivitiesB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="withdrawnDate" indFieldName="withdrawnB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="withdrawnReason" indFieldName="withdrawnB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="underwritingApprovedDate" indFieldName="underwritingApprovedB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="underwritingDeclinedDate" indFieldName="underwritingDeclinedB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="underwritingDeclineReason" indFieldName="underwritingDeclinedB" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="CI_ENT_ADDITIONAL_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>
    <page pageURI="/ciAddressList.do">
        <tags>
            <tag id="USAAddress_char1" indFieldName="USAAddress_char5" indFieldLocation="Page" action="Enabled/Disabled"/>
            <tag id="ForeignAddress_char1" indFieldName="ForeignAddress_char5" indFieldLocation="Page" action="Enabled/Disabled"/>
        </tags>
    </page>
    <page pageURI="/ciPhoneNumberList.do">
        <tags>
            <tag id="CI_PHNLST_ADDRW" indFieldName="addressExpiredB" indFieldLocation="Page" action="Disabled/Enabled"/>
            <tag id="CI_PHNLST_DELET" indFieldName="addressExpiredB" indFieldLocation="Page" action="Disabled/Enabled"/>
            <tag id="CI_PHNLST_SAVE" indFieldName="addressExpiredB" indFieldLocation="Page" action="Disabled/Enabled"/>
            <tag id="CI_PHNLST_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_PHNLST_ADDRW" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_PHNLST_DELET" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>
    <page pageURI="/fileactivitynotesmgr/maintainFileNotes.do">
        <tags>
           <tag id="CS_NOTES_GRID_ADD" indFieldName="isAddAvailable" indFieldLocation="Page" action="Enabled/Disabled" />
            <tag id="CS_NOTES_GRID_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row" action="Enabled/Disabled" defaultActionForNoRows="Disabled"/>
            <tag id="CS_NOTES_GRID_SAVE" indFieldName="isSaveAvailable" indFieldLocation="Page" action="Enabled/Disabled" />
            <tag id="isEditAvailable" indFieldName="isEditAvailable" indFieldLocation="Page" action="Show/Hide"/>
        </tags>
    </page>
    <page pageURI="/fileactivitynotesmgr/maintainActivityLog.do">
        <tags>
            <tag id="CS_NOTES_GRID_ADD" indFieldName="isAddAvailable" indFieldLocation="Page" action="Enabled/Disabled" />
            <tag id="CS_NOTES_GRID_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row" action="Enabled/Disabled" defaultActionForNoRows="Disabled" />
            <tag id="CS_NOTES_GRID_SAVE" indFieldName="isSaveAvailable" indFieldLocation="Page" action="Enabled/Disabled" />
            <tag id="isEditAvailable" indFieldName="isEditAvailable" indFieldLocation="Page" action="Show/Hide" />
        </tags>
    </page>

    <page pageURI="/entityAddlEmail.do">
        <tags>
            <tag id="CI_ETD_EMAIL_LIST_DEL" indFieldName="isDeleteAvailable" indFieldLocation="Row" action="Enabled/Disabled"
                 defaultActionForNoRows="Disabled"/>
            <tag id="CI_ETD_EMAIL_LIST_DEL" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_ETD_EMAIL_LIST_ADD" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_ETD_EMAIL_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>
    <page pageURI="/ciEntityPersonModify.do">
        <tags>
            <tag id="CI_ENT_PER_MOD_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_ENT_PER_MOD_CTP" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_ENT_PER_MOD_DUP" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>
    <page pageURI="/ciEntityOrgModify.do">
        <tags>
            <tag id="CI_ENT_ORG_MOD_SAVE" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_ENT_ORG_MOD_CTP" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
            <tag id="CI_ENT_ORG_MOD_DUP" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
        </tags>
    </page>
    <page pageURI="/maintainSpecialHandling.do">
        <tags>
            <tag id="CI_SPH_GIRD_ADD" indFieldName="isEntityReadOnlyYN" indFieldLocation="Page"
                 action="Disabled/Enabled"/>
